/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package code;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Antonio Casas Martínez
 */
public class principal extends javax.swing.JFrame {

    
    
    Border panel_margen = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow);
    
    int y = 0;
    
    ArrayList<Produkto> produktosf = new ArrayList<>();
    
    
    
    
    /** Creates new form principal */
    public principal() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        jPanel_fondo.setBorder(panel_margen);
        
        muestradProduktos();
       
    }

    public ArrayList<Produkto> getProductosList(){
        
        ArrayList<Produkto> list = new ArrayList<>();
        
        String selectQuery = "SELECT * FROM productos_BdD.productos;";
        
        
        Statement s;
        ResultSet r;
        
        try {
            s = Base_dDatos.getConnection().createStatement();
            
            r = s.executeQuery(selectQuery);
            
            Produkto produkto;
            
            while (r.next()){
                produkto = new Produkto(r.getInt("id"), r.getString("nombre"), r.getString("raiz"), r.getInt("cantidad"), r.getDouble("precio"), r.getInt("disponibilidad"));
                
                list.add(produkto);
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        produktosf = list;
        return list;
        
        
    }
    
    
    
    public void muestradProduktos(){
        
        ArrayList<Produkto> produktoslist = getProductosList();
        
        DefaultTableModel d = (DefaultTableModel) jTable_productos.getModel();

        d.setRowCount(0);
        
        Object[] fila = new Object[6];
        
        for (int i = 0; i < produktoslist.size(); i++) {
            
            fila[0] =  produktoslist.get(i).getId();
            fila[1] =  produktoslist.get(i).getNombre();
            fila[2] =  produktoslist.get(i).getRaiz();
            fila[4] =  produktoslist.get(i).getPrecio();
            fila[3] =  produktoslist.get(i).getCantidad();
            fila[5] =  produktoslist.get(i).getDisponibilidad();
            
        d.addRow(fila);
            
            
        }
        
         
        
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSpinner_myu = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jComboBox_raiz = new javax.swing.JComboBox<>();
        jTextField_precio = new javax.swing.JTextField();
        jButton_añadir = new javax.swing.JButton();
        jButton_editar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_buscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField_cantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_disp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton_antes = new javax.swing.JButton();
        jButton_después = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_fondo.setBackground(new java.awt.Color(204, 153, 255));
        jPanel_fondo.setPreferredSize(new java.awt.Dimension(1200, 600));

        jLabel1.setFont(new java.awt.Font("DIN Condensed", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CERRAR");
        jLabel1.setSize(new java.awt.Dimension(30, 30));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Raiz", "Cantidad", "Precio", "Disponibilidad"
            }
        ));
        jTable_productos.setGridColor(new java.awt.Color(0, 0, 0));
        jTable_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_productos);

        jLabel2.setFont(new java.awt.Font("American Typewriter", 0, 20)); // NOI18N
        jLabel2.setText("ID:");

        jSpinner_myu.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("American Typewriter", 0, 20)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("American Typewriter", 0, 20)); // NOI18N
        jLabel4.setText("Raíz:");

        jLabel5.setFont(new java.awt.Font("American Typewriter", 0, 20)); // NOI18N
        jLabel5.setText("Precio:");

        jLabel6.setFont(new java.awt.Font("American Typewriter", 0, 20)); // NOI18N
        jLabel6.setText("Cantidad:");

        jTextField_nombre.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N

        jComboBox_raiz.setEditable(true);
        jComboBox_raiz.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N
        jComboBox_raiz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leguminosa", "Cereal", "Semilla", "Chile", "Especie", "Animal" }));

        jTextField_precio.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N

        jButton_añadir.setBackground(new java.awt.Color(225, 0, 153));
        jButton_añadir.setFont(new java.awt.Font("American Typewriter", 1, 20)); // NOI18N
        jButton_añadir.setText("Añadir");
        jButton_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadirActionPerformed(evt);
            }
        });

        jButton_editar.setBackground(new java.awt.Color(225, 0, 153));
        jButton_editar.setFont(new java.awt.Font("American Typewriter", 1, 20)); // NOI18N
        jButton_editar.setText("Editar");
        jButton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarActionPerformed(evt);
            }
        });

        jButton_eliminar.setBackground(new java.awt.Color(225, 0, 153));
        jButton_eliminar.setFont(new java.awt.Font("American Typewriter", 1, 20)); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jButton_buscar.setBackground(new java.awt.Color(225, 0, 153));
        jButton_buscar.setFont(new java.awt.Font("American Typewriter", 1, 15)); // NOI18N
        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(225, 0, 153));
        jLabel8.setFont(new java.awt.Font("American Typewriter", 0, 30)); // NOI18N
        jLabel8.setText("BASE DE DATOS PARA EVANGELINA");

        jTextField_cantidad.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("American Typewriter", 0, 20)); // NOI18N
        jLabel7.setText("Disponibilidad:");

        jTextField_disp.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N

        jLabel9.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 153));
        jLabel9.setText("2= alta disponibilidad ");

        jLabel11.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 153));
        jLabel11.setText("1= poca disponibilidad ");

        jLabel12.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 153));
        jLabel12.setText("0= cero disponibilidad ");

        jButton_antes.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N
        jButton_antes.setText("<----");
        jButton_antes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_antesActionPerformed(evt);
            }
        });

        jButton_después.setFont(new java.awt.Font("American Typewriter", 0, 15)); // NOI18N
        jButton_después.setText("---->");
        jButton_después.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_despuésActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_fondoLayout = new javax.swing.GroupLayout(jPanel_fondo);
        jPanel_fondo.setLayout(jPanel_fondoLayout);
        jPanel_fondoLayout.setHorizontalGroup(
            jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(228, 228, 228)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_fondoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner_myu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229)
                        .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_fondoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                                .addComponent(jButton_antes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_después, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_fondoLayout.createSequentialGroup()
                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(22, 22, 22)
                                .addComponent(jComboBox_raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel_fondoLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(24, 24, 24)
                                        .addComponent(jTextField_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel_fondoLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel_fondoLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton_eliminar)))
                .addContainerGap())
        );
        jPanel_fondoLayout.setVerticalGroup(
            jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_fondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_myu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_después)
                            .addComponent(jButton_antes))
                        .addGap(104, 104, 104))
                    .addGroup(jPanel_fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox_raiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_disp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(118, 118, 118)
                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_eliminar)
                            .addComponent(jButton_editar))
                        .addGap(125, 125, 125))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1341, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here
       
       // if(vacio()){
                int id = Integer.valueOf(jSpinner_myu.getValue().toString());
                String selectQuery = "SELECT * FROM productos_BdD.productos WHERE `id` ="+id;


                try {
                    Statement s = Base_dDatos.getConnection().createStatement();
                    ResultSet r = s.executeQuery(selectQuery);

               
                    
                    if(r.next()){

                        jTextField_nombre.setText(r.getString("nombre"));
                        jComboBox_raiz.setSelectedItem(r.getString("raiz"));
                        jTextField_cantidad.setText(r.getString("cantidad"));
                        jTextField_precio.setText(String.valueOf(r.getDouble("precio")));
                        jTextField_disp.setText(r.getString("disponibilidad"));




                    }else{
                        System.out.println("No existe un producto con este id");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                }
        //}
       // else{
          //  System.out.println("Uno o más espacios estan vacíos");
       // }
        
        
        
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:
        
        if(Integer.valueOf(jSpinner_myu.getValue().toString())  > 0){
            
                Integer id = Integer.valueOf(jSpinner_myu.getValue().toString());

                String elimniarQuery = "DELETE FROM `productos_BdD`.`productos` WHERE `id` =?"; 

                    try {
                        PreparedStatement pre = Base_dDatos.getConnection().prepareStatement(elimniarQuery);

                        pre.setInt(1, id);


                        if (pre.executeUpdate() > 0) {
                                                muestradProduktos();

                            System.out.println("Producto Eliminado");
                            casillas();

                        }
                        else{
                            System.out.println("Intento falido ");
                        } 



                    } catch (SQLException ex) {
                        Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
        }else{
            System.out.println("Ingresa la id ");
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarActionPerformed
       
            
                Integer id = Integer.valueOf(jSpinner_myu.getValue().toString());
                String nombre = jTextField_nombre.getText();
                String raiz = jComboBox_raiz.getSelectedItem().toString();
                Integer cantidad = Integer.valueOf(jTextField_cantidad.getText());
                Double price = Double.valueOf(jTextField_precio.getText());
                Integer disponibilidad = Integer.valueOf(jTextField_disp.getText());

                String actualizarQuery = "UPDATE `productos_BdD`.`productos` SET `nombre` =?, `raiz` =?, `cantidad` =?, `precio` =?, `disponibilidad` =? WHERE `id` =?"; 

                    try {
                        PreparedStatement pre = Base_dDatos.getConnection().prepareStatement(actualizarQuery);

                        pre.setString(1, nombre);
                        pre.setString(2, raiz);
                        pre.setInt(   3, cantidad);
                        pre.setDouble(4, price);
                        pre.setInt(5, disponibilidad);
                        pre.setInt(6, id);


                        if (pre.executeUpdate() > 0) {
                            muestradProduktos();
                            System.out.println("Producto Actualizado");
                        }
                        else{
                            System.out.println("Intento falido ");
                        } 



                    } catch (SQLException ex) {
                        Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
            }
   
        
        
    }//GEN-LAST:event_jButton_editarActionPerformed

    private void jButton_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadirActionPerformed
        // TODO add your handling code here
        
        //if(vacio()){
                String nombre = jTextField_nombre.getText();
                String raiz = jComboBox_raiz.getSelectedItem().toString();
                Integer cantidad = Integer.valueOf(jTextField_cantidad.getText());
                Double price = Double.valueOf(jTextField_precio.getText());
                Integer disponibilidad = Integer.valueOf(jTextField_disp.getText().toString());

                String insertarQuery = "INSERT INTO `productos_BdD`.`productos`(`nombre`, `raiz`, `cantidad`, `precio`, `disponibilidad`) VALUES (?,?,?,?,?)"; 

                try {
                    PreparedStatement pre = Base_dDatos.getConnection().prepareStatement(insertarQuery);

                    pre.setString(1, nombre);
                    pre.setString(2, raiz);
                    pre.setInt(   3, cantidad);
                    pre.setDouble(4, price);
                    pre.setInt(5, disponibilidad);


                    if (pre.executeUpdate() > 0) {
                                            muestradProduktos();

                        System.out.println("Nuevo Producto Añadido");
                    }
                    else{
                        System.out.println("Intento falido ");
                    } 



                } catch (SQLException ex) {
                    Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                }
        //}else{
          //  System.out.println("Ingresa la id ");
        //}
        
    }//GEN-LAST:event_jButton_añadirActionPerformed

    
    
  
    
    
    
    
    
    
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTable_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productosMouseClicked
        // TODO   add your handling code here:
        int x = jTable_productos.getSelectedRow();
        enseñodProduktos(x);     
        
        y = x;
        
    }//GEN-LAST:event_jTable_productosMouseClicked

    
    
    
    private void jButton_despuésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_despuésActionPerformed
        // TODO add your handling code here:
        
        y ++ ;
        
        if (y > getProductosList().size()-1) {
            
            y=getProductosList().size()-1;
        }
        
        enseñodProduktos(y);
        
        
        jTable_productos.setRowSelectionInterval(y ,y);
        
    }//GEN-LAST:event_jButton_despuésActionPerformed

    private void jButton_antesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_antesActionPerformed
        // TODO add your handling code here:
        
        y -- ;
        
        if (y < 0) {
            
            y=0;
        }
        
        enseñodProduktos(y);
                jTable_productos.setRowSelectionInterval(y ,y);

    }//GEN-LAST:event_jButton_antesActionPerformed

    
    public void enseñodProduktos (int index){
       
        jSpinner_myu.setValue(getProductosList().get(index).getId());
        jTextField_nombre.setText(getProductosList().get(index).getNombre());
        jComboBox_raiz.setSelectedItem(getProductosList().get(index).getRaiz());;
        jTextField_cantidad.setText(getProductosList().get(index).getCantidad().toString());
        
        Double g = getProductosList().get(index).getPrecio();
        jTextField_precio.setText(g+"");
   
        Integer j = getProductosList().get(index).getDisponibilidad();
        jTextField_disp.setText(j+"");
        
    }
    
    public void casillas(){
        
        jSpinner_myu.setValue(0);
        jTextField_nombre.setText("");
        jTextField_cantidad.setText("");
        jComboBox_raiz.setSelectedItem(0);
        jTextField_precio.setText("");
        jTextField_disp.setText("");
        
    } 
    
    public boolean vacio (){
        
        String nombre = jTextField_nombre.getText().trim();
        String cantidad = jTextField_cantidad.getText().trim();
        String precio = jTextField_precio.getText().trim();
        String disp = jTextField_disp.getName().trim();
     
        if(nombre.equals("") || cantidad.equals("") || precio.equals("") || disp.equals("") ){
            
            return false;
            
        }else{
            
            return true;
            
        }
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_antes;
    private javax.swing.JButton jButton_añadir;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_después;
    private javax.swing.JButton jButton_editar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JComboBox<String> jComboBox_raiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_fondo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_myu;
    private javax.swing.JTable jTable_productos;
    private javax.swing.JTextField jTextField_cantidad;
    private javax.swing.JTextField jTextField_disp;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_precio;
    // End of variables declaration//GEN-END:variables

}
